### ISSUE TITLE
style: Regarding some UI fixes

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/taskwarrior-flutter#233] opened 2024-01-03 06:08 UTC
### 1. A minor typo in the sidebar
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/82613864-30e0-4c36-89ee-b13b482b25bb" height="500">

### 2. The Delete profile heading does not appear in Bold like the other headings
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/5e3ecb80-b19d-4410-aa1c-4e34c4d1dbef" height="200px">

### 3. The export icon shall be replaced, currently it signifies import instead of export
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/9beb03c5-5364-4c5f-a6bd-5300eb58c77b" height="200px">

### 4. There is an overflow in specific longer profiles, we can wrap these in some widgets like clip so that IDs do not overflow
<img src="https://github.com/CCExtractor/taskwarrior-flutter/assets/114338679/6b083828-0b1a-465f-862b-bb6ee1b176d6" height="500">

**Comment by nikkivirtuoso** [comment] 2024-01-03 06:56
i am interested in resolving this issue

**Comment by nikkivirtuoso** [comment] 2024-01-03 09:31
just created a pull request please review it

**Comment by nikkivirtuoso** [comment] 2024-01-03 09:33
<img width="1470" alt="Screenshot 2024-01-03 at 1 24 24 PM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/148634283/7247e46a-c91c-4611-9f7b-e543b00c5f3d">
<img width="1470" alt="Screenshot 2024-01-03 at 2 35 26 PM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/148634283/6653cc3a-2b05-42ef-8175-d285f6c69690">
<img width="1470" alt="Screenshot 2024-01-03 at 2 36 14 PM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/148634283/4c8b9f7b-8698-4643-8537-ce270c862562">
<img width="1470" alt="Screenshot 2024-01-03 at 2 36 38 PM" src="https://github.com/CCExtractor/taskwarrior-flutter/assets/148634283/74548f7e-e26d-43ef-899a-576429820fa0">

**Comment by Pavel401** [comment] 2024-01-03 12:09
@nikkivirtuoso , please refrain from submitting a pull request unless the issue is verified and has been assigned to you.

**Comment by Pavel401** [comment] 2024-01-03 12:11
@its-me-abhishek  I am closing this issue as it's fixed in this pr #234

**Closed** 2024-01-03 12:13 UTC
